on:
  pull_request:
    paths:
      - 'docs/src/public/**'
      - 'docs/build.gradle'
      - 'gradle/**'

jobs:
  check-doc-build:
    name: TDS Documentation Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Zulu JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: x64
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build docs using Gradle
        run: ./gradlew buildAllJekyllSites
      - uses: actions/upload-artifact@v2
        if: success()
        name: Upload a preview of the rendered html
        with:
          name: documentation_${{ github.sha }}
          path: docs/build/jekyll
