on: [pull_request]

jobs:
  check-assemble-adpotiumjdk-hs:
    name: Check fresh assemble of THREDDS Data Server Project (AdoptiumJDK-HS)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest Adoptium LTS releases
        java: [ 8, 11, 14 ]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Adoptium JDK ${{ matrix.java }} (hotspot) built for linux"
        run: curl -L "https://api.adoptopenjdk.net/v2/binary/releases/openjdk${{ matrix.java }}?openjdk_impl=hotspot&arch=x64&release=latest&type=jdk&os=linux" -o aojdk${{ matrix.java }}-hs.tar.gz
      - name: Setup Latest Adoptium JDK (hotspot) ${{ matrix.java }}
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          jdkFile: ./aojdk${{ matrix.java }}-hs.tar.gz
      - name: Print java version
        run: java -version
      - name: Build Gradle (refresh dependencies)
        run: ./gradlew assemble --refresh-dependencies

  tests-adpotopenjdk-hs:
    name: THREDDS Data Server Tests (AdoptiumJDK-HS)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest Adoptium LTS releases
        java: [ 8, 11, 14 ]
        # test against both old and new netCDF-Java api
        ncjnewapi: ['false', 'true']
        # test against tomcat 8.5.x and tomcat 9.x
        servletcontainer: [ 'tomcat85', 'tomcat9' ]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch latest Adoptium JDK ${{ matrix.java }} (hotspot) built for linux
        run: curl -L "https://api.adoptopenjdk.net/v2/binary/releases/openjdk${{ matrix.java }}?openjdk_impl=hotspot&arch=x64&release=latest&type=jdk&os=linux" -o aojdk${{ matrix.java }}-hs.tar.gz
      - name: Setup Latest Adoptium JDK (hotspot) ${{ matrix.java }}
        uses: actions/setup-java@master
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
          jdkFile: ./aojdk${{ matrix.java }}-hs.tar.gz
      - name: Print java version
        run: java -version
      - name: Install netCDF-C
        run: sudo apt update && sudo apt-get install libnetcdf-dev
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-${{ matrix.java }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-${{ matrix.java }}-gradle
      - name: Build and test with Gradle (${{ matrix.servletcontainer }})
        run: ./gradlew -Dtds.content.root.path=$CONTENT_DIR -Dtds.download.dir=$DOWNLOAD_DIR -Dtds.upload.dir=$UPLOAD_DIR -Dthredds.test.experimental.useNetcdfJavaBuilders=${{ matrix.ncjnewapi }} -Dtds.test.gretty.container=${{ matrix.servletcontainer }} --info --stacktrace testAll
        env:
          TRAVIS: 'true'
          CONTENT_DIR: ${{ github.workspace }}/tds/src/test/content
          DOWNLOAD_DIR: '/tmp/download'
          UPLOAD_DIR: '/tmp/upload'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: tds_JUnit_Results_${{ github.sha }}_AdoptOpenJDK-HS-${{ matrix.java }}-newApi-${{ matrix.ncjnewapi }}-${{ matrix.servletcontainer }}
          path: build/reports/allTests

  spotless:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Code Style Check with Gradle and Spotless
        run: ./gradlew clean spotlessCheck

