on: [pull_request]

jobs:
  netcdf-java-tests:
    name: netCDF-Java Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against latest 11 and 14 of zulu and temurin java
        java-version: [ 11 ]
        java-vendor: [ 'zulu', 'temurin' ]
        # test against tomcat 8.5.x and tomcat 9.x
        servletcontainer: [ 'tomcat85', 'tomcat9' ]
    steps:
      - uses: actions/checkout@v2
      - name: Build and test with Gradle (${{ matrix.java-vendor }} ${{ matrix.java-version }})
        uses: Unidata/thredds-test-action@v1
        with:
          java-vendor: ${{ matrix.java-vendor }}
          java-version: ${{ matrix.java-version }}
          build-tool: 'gradlew'
          test-command: '-Dtds.content.root.path=$CONTENT_DIR -Dtds.download.dir=$DOWNLOAD_DIR -Dtds.upload.dir=$UPLOAD_DIR -Dtds.test.gretty.container=${{ matrix.servletcontainer }} --info --stacktrace testAll'
        env:
          CONTENT_DIR: ${{ github.workspace }}/tds/src/test/content
          DOWNLOAD_DIR: '/tmp/download'
          UPLOAD_DIR: '/tmp/upload'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: tds_JUnit_Results_${{ github.sha }}_AdoptOpenJDK-HS-${{ matrix.java }}-newApi-${{ matrix.ncjnewapi }}-${{ matrix.servletcontainer }}
          path: build/reports/allTests



  spotless:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Code Style Check with Gradle and Spotless
        run: ./gradlew clean spotlessCheck
